
import { Question } from './types.ts';

export const DEFAULT_QUESTIONS: Question[] = [
    {"question":"1 × 1","questionType":"number","correctAnswer":1},{"question":"1 × 2","questionType":"number","correctAnswer":2},{"question":"1 × 3","questionType":"number","correctAnswer":3},{"question":"1 × 4","questionType":"number","correctAnswer":4},{"question":"1 × 5","questionType":"number","correctAnswer":5},{"question":"1 × 6","questionType":"number","correctAnswer":6},{"question":"1 × 7","questionType":"number","correctAnswer":7},{"question":"1 × 8","questionType":"number","correctAnswer":8},{"question":"1 × 9","questionType":"number","correctAnswer":9},{"question":"1 × 10","questionType":"number","correctAnswer":10},
    {"question":"2 × 1","questionType":"number","correctAnswer":2},{"question":"2 × 2","questionType":"number","correctAnswer":4},{"question":"2 × 3","questionType":"number","correctAnswer":6},{"question":"2 × 4","questionType":"number","correctAnswer":8},{"question":"2 × 5","questionType":"number","correctAnswer":10},{"question":"2 × 6","questionType":"number","correctAnswer":12},{"question":"2 × 7","questionType":"number","correctAnswer":14},{"question":"2 × 8","questionType":"number","correctAnswer":16},{"question":"2 × 9","questionType":"number","correctAnswer":18},{"question":"2 × 10","questionType":"number","correctAnswer":20},
    {"question":"3 × 1","questionType":"number","correctAnswer":3},{"question":"3 × 2","questionType":"number","correctAnswer":6},{"question":"3 × 3","questionType":"number","correctAnswer":9},{"question":"3 × 4","questionType":"number","correctAnswer":12},{"question":"3 × 5","questionType":"number","correctAnswer":15},{"question":"3 × 6","questionType":"number","correctAnswer":18},{"question":"3 × 7","questionType":"number","correctAnswer":21},{"question":"3 × 8","questionType":"number","correctAnswer":24},{"question":"3 × 9","questionType":"number","correctAnswer":27},{"question":"3 × 10","questionType":"number","correctAnswer":30},
    {"question":"4 × 1","questionType":"number","correctAnswer":4},{"question":"4 × 2","questionType":"number","correctAnswer":8},{"question":"4 × 3","questionType":"number","correctAnswer":12},{"question":"4 × 4","questionType":"number","correctAnswer":16},{"question":"4 × 5","questionType":"number","correctAnswer":20},{"question":"4 × 6","questionType":"number","correctAnswer":24},{"question":"4 × 7","questionType":"number","correctAnswer":28},{"question":"4 × 8","questionType":"number","correctAnswer":32},{"question":"4 × 9","questionType":"number","correctAnswer":36},{"question":"4 × 10","questionType":"number","correctAnswer":40},
    {"question":"5 × 1","questionType":"number","correctAnswer":5},{"question":"5 × 2","questionType":"number","correctAnswer":10},{"question":"5 × 3","questionType":"number","correctAnswer":15},{"question":"5 × 4","questionType":"number","correctAnswer":20},{"question":"5 × 5","questionType":"number","correctAnswer":25},{"question":"5 × 6","questionType":"number","correctAnswer":30},{"question":"5 × 7","questionType":"number","correctAnswer":35},{"question":"5 × 8","questionType":"number","correctAnswer":40},{"question":"5 × 9","questionType":"number","correctAnswer":45},{"question":"5 × 10","questionType":"number","correctAnswer":50},
    {"question":"6 × 1","questionType":"number","correctAnswer":6},{"question":"6 × 2","questionType":"number","correctAnswer":12},{"question":"6 × 3","questionType":"number","correctAnswer":18},{"question":"6 × 4","questionType":"number","correctAnswer":24},{"question":"6 × 5","questionType":"number","correctAnswer":30},{"question":"6 × 6","questionType":"number","correctAnswer":36},{"question":"6 × 7","questionType":"number","correctAnswer":42},{"question":"6 × 8","questionType":"number","correctAnswer":48},{"question":"6 × 9","questionType":"number","correctAnswer":54},{"question":"6 × 10","questionType":"number","correctAnswer":60},
    {"question":"7 × 1","questionType":"number","correctAnswer":7},{"question":"7 × 2","questionType":"number","correctAnswer":14},{"question":"7 × 3","questionType":"number","correctAnswer":21},{"question":"7 × 4","questionType":"number","correctAnswer":28},{"question":"7 × 5","questionType":"number","correctAnswer":35},{"question":"7 × 6","questionType":"number","correctAnswer":42},{"question":"7 × 7","questionType":"number","correctAnswer":49},{"question":"7 × 8","questionType":"number","correctAnswer":56},{"question":"7 × 9","questionType":"number","correctAnswer":63},{"question":"7 × 10","questionType":"number","correctAnswer":70},
    {"question":"8 × 1","questionType":"number","correctAnswer":8},{"question":"8 × 2","questionType":"number","correctAnswer":16},{"question":"8 × 3","questionType":"number","correctAnswer":24},{"question":"8 × 4","questionType":"number","correctAnswer":32},{"question":"8 × 5","questionType":"number","correctAnswer":40},{"question":"8 × 6","questionType":"number","correctAnswer":48},{"question":"8 × 7","questionType":"number","correctAnswer":56},{"question":"8 × 8","questionType":"number","correctAnswer":64},{"question":"8 × 9","questionType":"number","correctAnswer":72},{"question":"8 × 10","questionType":"number","correctAnswer":80},
    {"question":"9 × 1","questionType":"number","correctAnswer":9},{"question":"9 × 2","questionType":"number","correctAnswer":18},{"question":"9 × 3","questionType":"number","correctAnswer":27},{"question":"9 × 4","questionType":"number","correctAnswer":36},{"question":"9 × 5","questionType":"number","correctAnswer":45},{"question":"9 × 6","questionType":"number","correctAnswer":54},{"question":"9 × 7","questionType":"number","correctAnswer":63},{"question":"9 × 8","questionType":"number","correctAnswer":72},{"question":"9 × 9","questionType":"number","correctAnswer":81},{"question":"9 × 10","questionType":"number","correctAnswer":90},
    {"question":"10 × 1","questionType":"number","correctAnswer":10},{"question":"10 × 2","questionType":"number","correctAnswer":20},{"question":"10 × 3","questionType":"number","correctAnswer":30},{"question":"10 × 4","questionType":"number","correctAnswer":40},{"question":"10 × 5","questionType":"number","correctAnswer":50},{"question":"10 × 6","questionType":"number","correctAnswer":60},{"question":"10 × 7","questionType":"number","correctAnswer":70},{"question":"10 × 8","questionType":"number","correctAnswer":80},{"question":"10 × 9","questionType":"number","correctAnswer":90},{"question":"10 × 10","questionType":"number","correctAnswer":100}
];